### ISSUE TITLE
how can I run speech2gesture.py

### ISSUE THREAD

**Issue by wangzheliu** [chahuja/mix-stage#2]
can you give some advice?

**Comment by chahuja** [comment]
I would recommend using a sister repository to run that script which can be found [here](https://github.com/chahuja/aisle/blob/main/src/jobs/speech2gesture.py)

**Comment by jgai284** [comment]
Hi, I'm a research student who wants to train speech2gesture using PATS. Do I just need to execute the link you posted above and that's all hopefully?

**Comment by jgai284** [comment]
I have another question, I can't execute pip install -r requirements.txt. I'm using Python 3.11.9, do I need to switch to an earlier version?
