### ISSUE TITLE
Problems on loading data 'oliver/100992.h5'

### ISSUE THREAD

**Issue by Amazingren** [chahuja/mix-stage#5]
Hi @chahuja, 
Thanks for your impressive work on this, I really appreciate it.
While when I want to have a try of your codebase, it occurs the same problem on both training or inference by your pre-trained  checkpoints like follows:

![image](https://user-images.githubusercontent.com/31409716/126004593-a807b283-0c23-4542-9228-d22c19b2bc0d.png)

Actually,  any case which involves the speaker "Oliver"  would fail when training or inference. So could you please show me some suggestions on this? 

I am looking forward to your reply.

Many thanks~

**Comment by chahuja** [comment]
100992 is one of the intervals which does not have some of the features. Hence it is technically not part of the dataset. However, the code automatically ignores such files using a list of such intervals that can be found at `../dataset/groot/data/missing_intervals.h5`. It is likely that this file is somehow not available at the specified location and hence is giving the error. Let me know if this is true and we can debug from there

**Comment by Amazingren** [comment]
> 100992 is one of the intervals which does not have some of the features. Hence it is technically not part of the dataset. However, the code automatically ignores such files using a list of such intervals that can be found at `../dataset/groot/data/missing_intervals.h5`. It is likely that this file is somehow not available at the specified location and hence is giving the error. Let me know if this is true and we can debug from there

Thanks for the kind reply, I already put 'missing_intervals.h5' under `../dataset/groot/data` folder, but it still reports the same problem. Is there any other suggestion?  Anyway, thanks a lot!

**Comment by chahuja** [comment]
Try inserting a breakpoint [here](https://github.com/chahuja/mix-stage/blob/master/src/data/dataUtils.py#L275). '100992' should exist in `missing_intervals` and not exist in either of `train_intervals`, `dev_intervals` or `test_intervals`. 

I am also attaching missing_intervals.h5 [here](https://cmu.box.com/shared/static/v3247j0vaoek5ttjc5ge02cmnrog2c9o.h5). Maybe you have an outdated version. Let me know replacing the existing missing_intervals.h5 works for you.

**Comment by Amazingren** [comment]
> Try inserting a breakpoint [here](https://github.com/chahuja/mix-stage/blob/master/src/data/dataUtils.py#L275). '100992' should exist in `missing_intervals` and not exist in either of `train_intervals`, `dev_intervals` or `test_intervals`.
> 
> I am also attaching missing_intervals.h5 [here](https://cmu.box.com/shared/static/v3247j0vaoek5ttjc5ge02cmnrog2c9o.h5). Maybe you have an outdated version. Let me know replacing the existing missing_intervals.h5 works for you.

Hi @chahuja,  to replace the 'missing_intervals.h5' file works for me! Many thanks to you!
